### ISSUE TITLE
Getting error while running srsgnb

### ISSUE THREAD

**Issue by Aniket621** [srsran/srsRAN_Project#238] opened 2023-10-05 04:34 UTC
### Discussed in https://github.com/srsran/srsRAN_Project/discussions/235

<div type='discussions-op-text'>

<sup>Originally posted by **Aniket621** October  4, 2023</sup>
Hi all, 

I am trying to build srsgnb and build is successfull but getting error while running srsgnb. As per gnb logs CU-CP and CU-UP Starting succcessfully and SCTP and NGAP interface showing up as per whireshark. 

gnb.logs 

![image](https://github.com/srsran/srsRAN_Project/assets/104416203/a77c3840-2f1f-4bcc-ac08-fc82d852e7de)

wireshark logs 
![image](https://github.com/srsran/srsRAN_Project/assets/104416203/f32c4a43-2acb-4f41-bc88-4088e52fee3a)

But getting error while running gnb and it's giving error  No radio resource available and unable to create radio session although zmq and czmq both are installed . 

![image](https://github.com/srsran/srsRAN_Project/assets/104416203/66938936-b4e1-44a9-b228-1f607ad00bff)

Kindly help above this error.
</div>

**Comment by robertfalkenberg** [comment] 2023-10-05 04:47
Duplicate of #235

**Closed by robertfalkenberg** 2023-10-05 04:47 UTC
